### PR TITLE
Give proxy precedence over history api fallback

### PR DESCRIPTION
**Pull request by chooty**
Currently the middleware used for the --fallback option is executed before the --proxy middleware. This causes all requests to return index.html, even the ones to the path specified with --proxy-route, in effect making it so --proxy has no effect at all in combination with --fallback. 
This change switches the middlewares around so the proxy middleware will proxy any requests to its specified path.

### CODE REVIEW

**Comment by piotrwitek** [comment]
@chooty Hi, thanks for contribution, I planned to add some `superagent` tests to confirm this functionality is working as I'm not using it in my projects with this dev server.

So please let me add some tests first to confirm that it is working and then I gonna merge this PR.

Thanks!

**Comment by piotrwitek** [comment]
@chooty I have fixed some issues and added tests including your case, it looks like your issue is already fixed.
Can you please update to newest release (v1.0.0-rc5) and confirm it is fixed?

**Comment by chooty** [comment]
@piotrwitek It works so long as the request to the proxied route doesn't have an accept-header that the fallback middleware will pick up. 
I would still expect it to proxy the request even if the client sends accept: \*/\*, which it doesn't now from what I can see. It's not a big issue however since it's easy to work around on the client.

**Comment by piotrwitek** [comment]
@chooty thanks for elaborating, so I understand that accept header is having impact here, I would like to fix it, can you help me with improving my tests cases?
Here is the test case: https://github.com/piotrwitek/jspm-hmr/blob/master/test/jspm-hmr-server.spec.ts

Could you give me hints to have a breaking test I could test is catching your specific scenario?

Thanks a lot!

**Comment by chooty** [comment]
@piotrwitek I've merged 1.0.0-rc5 and updated the test for the combination of fallback and proxy. Please have a look.

**Comment by piotrwitek** [comment]
@chooty thanks a lot for helping with this edge case 👍 
looks good to me

**Review by piotrwitek — APPROVED** [review]

**Comment by piotrwitek** [comment]
@chooty gonna push a new release with this change later 'rc6'

**Pull request merged**
